// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  alt: string;
  author: string;
  black: string;
  cyan_4: string;
  cyan_8: string;
  cyan_base: string;
  date: string;
  description: string;
  details: string;
  error: string;
  meta: string;
  next_blog_card: string;
  normal_color: string;
  photo: string;
  pink_base: string;
  purple_base: string;
  'read-more': string;
  success: string;
  tags: string;
  volcano_base: string;
  warning: string;
}
export const cssExports: CssExports;
export default cssExports;
