// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  black: string;
  cyan_4: string;
  cyan_8: string;
  cyan_base: string;
  error: string;
  normal_color: string;
  pink_base: string;
  purple_base: string;
  success: string;
  volcano_base: string;
  warning: string;
}
export const cssExports: CssExports;
export default cssExports;
